import React from 'react';
import renderer from 'react-test-renderer';

import { CreateDocument as CreateDocumentDark } from './components/pictograms/dark/CreateDocument';
import { Email as EmailDark } from './components/pictograms/dark/Email';
import { Print as PrintDark } from './components/pictograms/dark/Print';
import { Sign as SignDark } from './components/pictograms/dark/Sign';
import { Scan as ScanDark } from './components/pictograms/dark/Scan';
import { PhoneTap as PhoneTapDark } from './components/pictograms/dark/PhoneTap';
import { EditDocument as EditDocumentDark } from './components/pictograms/dark/EditDocument';
import { SendDoc as SendDocDark } from './components/pictograms/dark/SendDoc';
import { ShareData as ShareDataDark } from './components/pictograms/dark/ShareData';
import { SignedDoc as SignedDocDark } from './components/pictograms/dark/SignedDoc';
import { SignedDocMulti as SignedDocMultiDark } from './components/pictograms/dark/SignedDocMulti';
import { Signer as SignerDark } from './components/pictograms/dark/Signer';
import { UnknownSigner as UnknownSignerDark } from './components/pictograms/dark/UnknownSigner';
import { Approver as ApproverDark } from './components/pictograms/dark/Approver';

import { Audit as AuditDark } from './components/pictograms/dark/Audit';
import { OnlineSign as OnlineSignDark } from './components/pictograms/dark/OnlineSign';
import { DownloadDoc as DownloadDocDark } from './components/pictograms/dark/DownloadDoc';
import { Time as TimeDark } from './components/pictograms/dark/Time';
import { Speed as SpeedDark } from './components/pictograms/dark/Speed';
import { Wetlink as WetlinkDark } from './components/pictograms/dark/Wetlink';
import { Online as OnlineDark } from './components/pictograms/dark/Online';
import { Secure as SecureDark } from './components/pictograms/dark/Secure';
import { Link as LinkDark } from './components/pictograms/dark/Link';
import { SingleDoc as SingleDocDark } from './components/pictograms/dark/SingleDoc';
import { MultiDocs as MultiDocsDark } from './components/pictograms/dark/MultiDocs';
import { Duplicate as DuplicateDark } from './components/pictograms/dark/Duplicate';
import { AddPage as AddPageDark } from './components/pictograms/dark/AddPage';
import { MailStack as MailStackDark } from './components/pictograms/dark/MailStack';
import { UploadPictogram as UploadPictogramDark } from './components/pictograms/dark/UploadPictogram';
import { DownloadCloud as DownloadCloudDark } from './components/pictograms/dark/DownloadCloud';
import { Lightbulb as LightbulbDark } from './components/pictograms/dark/Lightbulb';
import { Shield as ShieldDark } from './components/pictograms/dark/Shield';
import { ReloadPage as ReloadPageDark } from './components/pictograms/dark/ReloadPage';
import { SendPage as SendPageDark } from './components/pictograms/dark/SendPage';
import { FrozenDoc as FrozenDocDark } from './components/pictograms/dark/FrozenDoc';
import { Search as SearchDark } from './components/pictograms/dark/Search';
import { FolderAlt as FolderAltDark } from './components/pictograms/dark/FolderAlt';
import { Folder as FolderDark } from './components/pictograms/dark/Folder';
import { FolderAlt2 as FolderAlt2Dark } from './components/pictograms/dark/FolderAlt2';
import { FolderAlt3 as FolderAlt3Dark } from './components/pictograms/dark/FolderAlt3';
import { Settings as SettingsDark } from './components/pictograms/dark/Settings';
import { SettingsAlt2 as SettingsAlt2Dark } from './components/pictograms/dark/SettingsAlt2';
import { OnlineSecurity as OnlineSecurityDark } from './components/pictograms/dark/OnlineSecurity';
import { Diamond as DiamondDark } from './components/pictograms/dark/Diamond';
import { Overview as OverviewDark } from './components/pictograms/dark/Overview';
import { SecureV1 as SecureV1Dark } from './components/pictograms/dark/SecureV1';
import { PageCog as PageCogDark } from './components/pictograms/dark/PageCog';
import { HandGlobe as HandGlobeDark } from './components/pictograms/dark/HandGlobe';
import { HandDocument as HandDocumentDark } from './components/pictograms/dark/HandDocument';

import { MoneyCheckBoxes as MoneyCheckBoxesDark } from './components/pictograms/dark/MoneyCheckBoxes';
import { MoneyLineGraphV2 as MoneyLineGraphV2Dark } from './components/pictograms/dark/MoneyLineGraphV2';
import { MoneyLineGraphV1 as MoneyLineGraphV1Dark } from './components/pictograms/dark/MoneyLineGraphV1';
import { MoneyBarChart as MoneyBarChartDark } from './components/pictograms/dark/MoneyBarChart';
import { EconomicGrowth as EconomicGrowthDark } from './components/pictograms/dark/EconomicGrowth';
import { HandMoney as HandMoneyDark } from './components/pictograms/dark/HandMoney';
import { SustainablePageV2 as SustainablePageV2Dark } from './components/pictograms/dark/SustainablePageV2';
import { DocumentConnect as DocumentConnectDark } from './components/pictograms/dark/DocumentConnect';
import { SustainablePageV1 as SustainablePageV1Dark } from './components/pictograms/dark/SustainablePageV1';
import { SustainableLightbulb as SustainableLightbulbDark } from './components/pictograms/dark/SustainableLightbulb';
import { MoneyPage as MoneyPageDark } from './components/pictograms/dark/MoneyPage';
import { OnlineApproval as OnlineApprovalDark } from './components/pictograms/dark/OnlineApproval';
import { ChatBubbleV1 as ChatBubbleV1Dark } from './components/pictograms/dark/ChatBubbleV1';
import { ChatBubbleV2 as ChatBubbleV2Dark } from './components/pictograms/dark/ChatBubbleV2';
import { GDPR as GDPRDark } from './components/pictograms/dark/GDPR';
import { IndustryBuildingsV1 as IndustryBuildingsV1Dark } from './components/pictograms/dark/IndustryBuildingsV1';
import { IndustryBuildingsV2 as IndustryBuildingsV2Dark } from './components/pictograms/dark/IndustryBuildingsV2';
import { IndustryBuildingsV3 as IndustryBuildingsV3Dark } from './components/pictograms/dark/IndustryBuildingsV3';
import { SustainableCycle as SustainableCycleDark } from './components/pictograms/dark/SustainableCycle';

import { PadlockCheck as PadlockCheckDark } from './components/pictograms/dark/PadlockCheck';
import { PadlockShield as PadlockShieldDark } from './components/pictograms/dark/PadlockShield';
import { PadlockShieldAndStars as PadlockShieldAndStarsDark } from './components/pictograms/dark/PadlockShieldAndStars';

import { HandChatBubbleQuestion as HandChatBubbleQuestionDark } from './components/pictograms/dark/HandChatBubbleQuestion';
import { HandChatBubbleText as HandChatBubbleTextDark } from './components/pictograms/dark/HandChatBubbleText';
import { HandChatBubbleDots as HandChatBubbleDotsDark } from './components/pictograms/dark/HandChatBubbleDots';

import { UploadDocumentSuccessful as UploadDocumentSuccessfulDark } from './components/pictograms/dark/UploadDocumentSuccessful';
import { UploadDocumentFailed as UploadDocumentFailedDark } from './components/pictograms/dark/UploadDocumentFailed';
import { UploadDocumentWarning as UploadDocumentWarningDark } from './components/pictograms/dark/UploadDocumentWarning';
import { UploadDocumentPreUpload as UploadDocumentPreUploadDark } from './components/pictograms/dark/UploadDocumentPreUpload';

import { UploadImagePreUploadRectangle as UploadImagePreUploadRectangleDark } from './components/pictograms/dark/UploadImagePreUploadRectangle';
import { UploadImageSuccessfulRectangle as UploadImageSuccessfulRectangleDark } from './components/pictograms/dark/UploadImageSuccessfulRectangle';
import { UploadImageWarningRectangle as UploadImageWarningRectangleDark } from './components/pictograms/dark/UploadImageWarningRectangle';
import { UploadImageFailedRectangle as UploadImageFailedRectangleDark } from './components/pictograms/dark/UploadImageFailedRectangle';
import { UploadImagePreUploadSquare as UploadImagePreUploadSquareDark } from './components/pictograms/dark/UploadImagePreUploadSquare';
import { UploadImageSuccessfulSquare as UploadImageSuccessfulSquareDark } from './components/pictograms/dark/UploadImageSuccessfulSquare';
import { UploadImageWarningSquare as UploadImageWarningSquareDark } from './components/pictograms/dark/UploadImageWarningSquare';
import { UploadImageFailedSquare as UploadImageFailedSquareDark } from './components/pictograms/dark/UploadImageFailedSquare';